<?php
/**
*
* @package install
* @version 0.9.05
* @copyright (c) 2011-12 BrokenCrust bc@brokencrust.com
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
* Original copyright: (c) 2005 phpBB Group
*/

if (!defined('IN_PHPBB')) { exit; }

include($phpbb_root_path . 'config.' . $phpEx);
unset($dbpasswd);

$convertor_data = array(
	'forum_name'    => 'DragonflyCMS 9.2.x',
	'version'       => '0.9.04',
	'phpbb_version' => '3.0.10',
	'author'        => '<a href="http://brokencrust.com">BrokenCrust</a>',
	'dbms'          => $dbms,
	'dbhost'        => $dbhost,
	'dbport'        => $dbport,
	'dbuser'        => $dbuser,
	'dbpasswd'      => '',
	'dbname'        => 'df',
	'table_prefix'  => 'cms_',
	'forum_path'    => '../../df/modules/Forums/',
	'author_notes'  => 'Welcome to the Dragonfly (standard Forums) to phpBB3 convertor. Set the former board path to the forums module directory.',
);

$tables = array(
	'bbattachments',
	'bbattachments_desc',
	'bbauth_access',
	'bbcategories',
	'bbextension_groups',
	'bbextensions',
	'bbforum_prune',
	'bbforums',
	'bbgroups',
	'bbposts',
	'bbposts_text',
	'bbprivmsgs',
	'bbprivmsgs_text',
	'bbranks',
	'bbsmilies',
	'bbtopics',
	'bbtopics_watch',
	'bbtopic_icons',
	'bbuser_group',
	'bbvote_desc',
	'bbvote_results',
	'bbvote_voters',
	'bbwords',
	'users'
);

$config_schema = array(
	'table_name'   => 'bbconfig',
	'table_format' => array('config_name' => 'config_value'),
	'settings'     => array(
		'allow_avatar_local'  => 'allow_avatar_local',
		'allow_avatar_remote' => 'allow_avatar_remote',
		'allow_avatar_upload' => 'allow_avatar_upload',
		'allow_bbcode'        => 'allow_bbcode',
		'allow_namechange'    => 'allow_namechange',
		'allow_privmsg'       => 'not(privmsg_disable)',
		'allow_sig'           => 'allow_sig',
		'allow_smilies'       => 'allow_smilies',
		'avatar_filesize'     => 'avatar_filesize',
		'avatar_max_height'   => 'avatar_max_height',
		'avatar_max_width'    => 'avatar_max_width',
		'board_disable'       => 'board_disable',
		'board_email_form'    => 'board_email_form',
		'board_email_sig'     => 'board_email_sig',
		'board_startdate'     => 'board_startdate',
		'board_timezone'      => 'board_timezone',
		'coppa_enable'        => '!is_empty(coppa_mail)',
		'coppa_fax'           => 'coppa_fax',
		'coppa_mail'          => 'coppa_mail',
		'default_dateformat'  => 'default_dateformat',
		'enable_confirm'      => 'enable_confirm',
		'flood_interval'      => 'flood_interval',
		'gzip_compress'       => 'gzip_compress',
		'hot_threshold'       => 'hot_threshold',
		'max_poll_options'    => 'max_poll_options',
		'max_sig_chars'       => 'max_sig_chars',
		'override_user_style' => 'override_user_style',
		'pm_max_msgs'         => 'max_inbox_privmsgs',
		'posts_per_page'      => 'posts_per_page',
		'record_online_date'  => 'record_online_date',
		'record_online_users' => 'record_online_users',
		'require_activation'  => 'require_activation',
		'session_length'      => 'session_length',
		'site_desc'           => 'site_desc',
		'sitename'            => 'sitename',
		'smtp_delivery'       => 'smtp_delivery',
		'smtp_host'           => 'smtp_host',
		'smtp_password'       => 'smtp_password',
		'smtp_username'       => 'smtp_username',
		'topics_per_page'     => 'topics_per_page'
	),
);

$test_file = 'modcp.php';

if (!$get_info) {

	$src_db->sql_return_on_error(false);

	$sql = "SELECT user_id FROM {$convert->src_table_prefix}users WHERE user_id = 1";
	$result = $src_db->sql_query($sql);
	$user_id = (int) $src_db->sql_fetchfield('user_id');
	$src_db->sql_freeresult($result);

	if ($user_id === 1) {
		$sql = "SELECT MAX(user_id) AS max_user_id FROM {$convert->src_table_prefix}users";
		$result = $src_db->sql_query($sql);
		$user_id = (int) $src_db->sql_fetchfield('max_user_id');
		$src_db->sql_freeresult($result);

		set_config('increment_user_id', ($user_id + 1), true);
	} else {
		set_config('increment_user_id', 0, true);
	}

	// Overwrite maximum avatar width/height
	@define('DEFAULT_AVATAR_X_CUSTOM', get_config_value('avatar_max_width'));
	@define('DEFAULT_AVATAR_Y_CUSTOM', get_config_value('avatar_max_height'));
	
	// additional table used only during conversion
	@define('USERCONV_TABLE', $table_prefix . 'userconv');

	$result = $src_db->sql_query("SELECT cfg_value FROM ".$convert->src_table_prefix."config_custom WHERE cfg_name = 'avatar' AND cfg_field= 'gallery_path'");
	$avatar_gallery_path = $src_db->sql_fetchfield('cfg_value');

	$result = $src_db->sql_query("SELECT cfg_value FROM ".$convert->src_table_prefix."config_custom WHERE cfg_name = 'avatar' AND cfg_field= 'path'");
	$avatar_path = $src_db->sql_fetchfield('cfg_value');

	$convertor = array(
		'test_file'           => 'viewtopic.php',
		'avatar_path'         => df_fix_module_path($avatar_path) . '/',
		'avatar_gallery_path' => df_fix_module_path($avatar_gallery_path) . '/gallery/',
		'smilies_path'        => df_fix_module_path(get_config_value('smilies_path')) . '/',
		'upload_path'         => df_fix_module_path('uploads/forums') . '/',
		'thumbnails'          => array('thumbs/', 't_'),
		'ranks_path'          => df_fix_module_path(''),
		'icons_path'          => df_fix_module_path(''),
		'query_first'         => array(
			array('target', $convert->truncate_statement . SEARCH_RESULTS_TABLE),
			array('target', $convert->truncate_statement . SEARCH_WORDLIST_TABLE),
			array('target', $convert->truncate_statement . SEARCH_WORDMATCH_TABLE),
			array('target', $convert->truncate_statement . LOG_TABLE),
		),
		'execute_first'       => '
			df_config_copy();
			get_config();
			phpbb_create_userconv_table();
			df_import_avatar_gallery();
			df_import_attach_config();
			df_insert_forums();
		',
		'execute_last'        =>
			array(
				'add_bots();',
				'update_folder_pm_count();',
				'update_unread_count();',
				"df_convert_authentication('start');",
				"df_convert_authentication('first');",
				"df_convert_authentication('second');",
				"df_convert_authentication('third');",
				"df_fix_post_attachement();",
				"df_remove_no_avatar();"
			),
		'schema'            => array(
			array(
				'target'        => USERCONV_TABLE,
				'query_first'   => array('target', $convert->truncate_statement . USERCONV_TABLE),
					array('user_id',        'users.user_id',  ''),
					array('username_clean', 'users.username', 'utf8_clean_string'),
			),
			array(
				'target'        => ATTACHMENTS_TABLE,
				'primary'       => 'bbattachments.attach_id',
				'query_first'   => array('target', $convert->truncate_statement . ATTACHMENTS_TABLE),
				'autoincrement' => 'attach_id',
					array('attach_id',         'bbattachments.attach_id',              ''),
					array('post_msg_id',       'bbattachments.post_id',                ''),
					array('topic_id',          'bbposts.topic_id',                     ''),
					array('in_message',        0,                                      ''),
					array('is_orphan',         0,                                      ''),
					array('poster_id',         'bbattachments.user_id_1 AS poster_id', 'df_user_id'),
					array('physical_filename', 'bbattachments_desc.physical_filename', 'import_attachment'),
					array('real_filename',     'bbattachments_desc.real_filename',     ''),
					array('download_count',    'bbattachments_desc.download_count',    ''),
					array('attach_comment',    'bbattachments_desc.comment',           'utf8_htmlspecialchars'),
					array('extension',         'bbattachments_desc.extension',         ''),
					array('mimetype',          'bbattachments_desc.mimetype',          ''),
					array('filesize',          'bbattachments_desc.filesize',          ''),
					array('filetime',          'bbattachments_desc.filetime',          'df_timezone_correction'),
					array('thumbnail',         'bbattachments_desc.thumbnail',         ''),
				'where'         => 'bbattachments_desc.attach_id = bbattachments.attach_id AND bbattachments.privmsgs_id = 0 AND bbposts.post_id = bbattachments.post_id',
				'group_by'      => 'bbattachments.attach_id'
			),
			array(
				'target'        => ATTACHMENTS_TABLE,
				'primary'       => 'bbattachments.attach_id',
				'autoincrement' => 'attach_id',
					array('attach_id',         'bbattachments.attach_id',              ''),
					array('post_msg_id',       'bbattachments.privmsgs_id',            ''),
					array('topic_id',          0,                                      ''),
					array('in_message',        1,                                      ''),
					array('is_orphan',         0,                                      ''),
					array('poster_id',         'bbattachments.user_id_1 AS poster_id', 'df_user_id'),
					array('physical_filename', 'bbattachments_desc.physical_filename', 'import_attachment'),
					array('real_filename',     'bbattachments_desc.real_filename',     ''),
					array('download_count',    'bbattachments_desc.download_count',    ''),
					array('attach_comment',    'bbattachments_desc.comment',           'utf8_htmlspecialchars'),
					array('extension',         'bbattachments_desc.extension',         ''),
					array('mimetype',          'bbattachments_desc.mimetype',          ''),
					array('filesize',          'bbattachments_desc.filesize',          ''),
					array('filetime',          'bbattachments_desc.filetime',          'df_timezone_correction'),
					array('thumbnail',         'bbattachments_desc.thumbnail',         ''),
				'where'         => 'bbattachments_desc.attach_id = bbattachments.attach_id AND bbattachments.post_id = 0',
				'group_by'      => 'bbattachments.attach_id'
			),
			array(
				'target'        => EXTENSIONS_TABLE,
				'query_first'   => array('target', $convert->truncate_statement . EXTENSIONS_TABLE),
				'autoincrement' => 'extension_id',
					array('extension_id', 'bbextensions.ext_id',    ''),
					array('group_id',     'bbextensions.group_id',  ''),
					array('extension',    'bbextensions.extension', ''),
			),
			array(
				'target'        => EXTENSION_GROUPS_TABLE,
				'query_first'   => array('target', $convert->truncate_statement . EXTENSION_GROUPS_TABLE),
				'autoincrement' => 'group_id',
					array('group_id',       'bbextension_groups.group_id',          ''),
					array('group_name',     'bbextension_groups.group_name',        'utf8_htmlspecialchars'),
					array('cat_id',         'bbextension_groups.cat_id',            'phpbb_attachment_category'),
					array('allow_group',    'bbextension_groups.allow_group',       ''),
					array('download_mode',  1,                                      ''),
					array('upload_icon',    '',                                     ''),
					array('max_filesize',   'bbextension_groups.max_filesize',      ''),
					array('allowed_forums', 'bbextension_groups.forum_permissions', 'phpbb_attachment_forum_perms'),
					array('allow_in_pm',    1,                                      ''),
			),
			array(
				'target'        => RANKS_TABLE,
				'query_first'   => array('target', $convert->truncate_statement . RANKS_TABLE),
				'autoincrement' => 'rank_id',
					array('rank_id',      'bbranks.rank_id',      ''),
					array('rank_title',   'bbranks.rank_title',   'utf8_htmlspecialchars'),
					array('rank_min',     'bbranks.rank_min',     array('typecast' => 'int', 'execute' => '{RESULT} = ({VALUE}[0] < 0) ? 0 : {VALUE}[0];')),
					array('rank_special', 'bbranks.rank_special', ''),
					array('rank_image',   'bbranks.rank_image',   'import_rank'),
			),
			array(
				'target'        => ICONS_TABLE,
				'query_first'   => array('target', $convert->truncate_statement . ICONS_TABLE),
				'autoincrement' => 'icons_id',
					array('icons_id',           'bbtopic_icons.icon_id',  ''),
					array('icons_url',          'bbtopic_icons.icon_url', 'df_import_icon'),
					array('icons_width',        19,                       ''),
					array('icons_height',       19,                       ''),
					array('icons_order',        'bbtopic_icons.icon_id',  ''),
					array('display_on_posting', 1,                        ''),
			),
			array(
				'target'        => TOPICS_TABLE,
				'query_first'   => array('target', $convert->truncate_statement . TOPICS_TABLE),
				'primary'       => 'bbtopics.topic_id',
				'autoincrement' => 'topic_id',
					array('topic_id',             'bbtopics.topic_id',                  ''),
					array('forum_id',             'bbtopics.forum_id',                  ''),
					array('icon_id',              'bbtopics.icon_id',                   ''),
					array('topic_poster',         'bbtopics.topic_poster AS poster_id', 'df_user_id'),
					array('topic_attachment',     'bbtopics.topic_attachment',          ''),
					array('topic_title',          'bbtopics.topic_title',               'df_entity_decode'),
					array('topic_time',           'bbtopics.topic_time',                'df_timezone_correction'),
					array('topic_views',          'bbtopics.topic_views',               ''),
					array('topic_replies',        'bbtopics.topic_replies',             ''),
					array('topic_replies_real',   'bbtopics.topic_replies',             ''),
					array('topic_last_post_id',   'bbtopics.topic_last_post_id',        ''),
					array('topic_status',         'bbtopics.topic_status',              'is_topic_locked'),
					array('topic_moved_id',       0,                                    ''),
					array('topic_type',           'bbtopics.topic_type',                'phpbb_convert_topic_type'),
					array('topic_first_post_id',  'bbtopics.topic_first_post_id',       ''),
					array('topic_last_view_time', 'bbposts.post_time',                  array('function1' => 'intval', 'function2' => 'df_timezone_correction')),
					array('poll_title',           'bbvote_desc.vote_text',              array('function1' => 'null_to_str', 'function2' => 'utf8_htmlspecialchars')),
					array('poll_start',           'bbvote_desc.vote_start',             'null_to_zero'),
					array('poll_length',          'bbvote_desc.vote_length',            'null_to_zero'),
					array('poll_max_options',     1,                                    ''),
					array('poll_vote_change',     0,                                    ''),
				'left_join'     =>  array ('bbtopics LEFT JOIN bbvote_desc ON bbtopics.topic_id = bbvote_desc.topic_id AND bbtopics.topic_vote = 1', 'bbtopics LEFT JOIN bbposts ON bbtopics.topic_last_post_id = bbposts.post_id', ),
				'where'         => 'bbtopics.topic_moved_id = 0',
			),
			array(
				'target'        => TOPICS_TABLE,
				'primary'       => 'bbtopics.topic_id',
				'autoincrement' => 'topic_id',
					array('topic_id',            'bbtopics.topic_id',                  ''),
					array('forum_id',            'bbtopics.forum_id',                  ''),
					array('icon_id',             0,                                    ''),
					array('topic_poster',        'bbtopics.topic_poster AS poster_id', 'df_user_id'),
					array('topic_attachment',    'bbtopics.topic_attachment',          ''),
					array('topic_title',         'bbtopics.topic_title',               'df_entity_decode'),
					array('topic_time',          'bbtopics.topic_time',                'df_timezone_correction'),
					array('topic_views',         'bbtopics.topic_views',               ''),
					array('topic_replies',       'bbtopics.topic_replies',             ''),
					array('topic_replies_real',  'bbtopics.topic_replies',             ''),
					array('topic_last_post_id',  'bbtopics.topic_last_post_id',        ''),
					array('topic_status',        ITEM_MOVED,                           ''),
					array('topic_moved_id',      'bbtopics.topic_moved_id',            ''),
					array('topic_type',          'bbtopics.topic_type',                'phpbb_convert_topic_type'),
					array('topic_first_post_id', 'bbtopics.topic_first_post_id',       ''),
					array('poll_title',          'bbvote_desc.vote_text',              array('function1' => 'null_to_str', 'function2' => 'utf8_htmlspecialchars')),
					array('poll_start',          'bbvote_desc.vote_start',             'null_to_zero'),
					array('poll_length',         'bbvote_desc.vote_length',            'null_to_zero'),
					array('poll_max_options',    1,                                    ''),
					array('poll_vote_change',    0,                                    ''),
				'left_join'     => 'bbtopics LEFT JOIN bbvote_desc ON bbtopics.topic_id = bbvote_desc.topic_id AND bbtopics.topic_vote = 1',
				'where'         => 'bbtopics.topic_moved_id <> 0',
			),
			array(
				'target'        => TOPICS_WATCH_TABLE,
				'primary'       => 'bbtopics_watch.topic_id',
				'query_first'   => array('target', $convert->truncate_statement . TOPICS_WATCH_TABLE),
					array('topic_id',      'bbtopics_watch.topic_id',      ''),
					array('user_id',       'bbtopics_watch.user_id',       'df_user_id'),
					array('notify_status', 'bbtopics_watch.notify_status', ''),
			),
			array(
				'target'        => SMILIES_TABLE,
				'query_first'   => array('target', $convert->truncate_statement . SMILIES_TABLE),
				'autoincrement' => 'smiley_id',
					array('smiley_id',          'bbsmilies.smilies_id', ''),
					array('code',               'bbsmilies.code',       array('function1' => 'phpbb_smilie_html_decode', 'function2' => 'utf8_htmlspecialchars')),
					array('emotion',            'bbsmilies.emoticon',   ''),
					array('smiley_url',         'bbsmilies.smile_url',  'import_smiley'),
					array('smiley_width',       'bbsmilies.smile_url',  'get_smiley_width'),
					array('smiley_height',      'bbsmilies.smile_url',  'get_smiley_height'),
					array('smiley_order',       'bbsmilies.smilies_id', ''),
					array('display_on_posting', 'bbsmilies.smilies_id', 'get_smiley_display'),
				'order_by'      => 'bbsmilies.smilies_id ASC',
			),
			array(
				'target'        => POLL_OPTIONS_TABLE,
				'primary'       => 'bbvote_results.vote_option_id',
				'query_first'   => array('target', $convert->truncate_statement . POLL_OPTIONS_TABLE),
					array('poll_option_id',    'bbvote_results.vote_option_id',      ''),
					array('topic_id',          'bbvote_desc.topic_id',               ''),
					array('',                  'bbtopics.topic_poster AS poster_id', 'df_user_id'),
					array('poll_option_text',  'bbvote_results.vote_option_text',    'utf8_htmlspecialchars'),
					array('poll_option_total', 'bbvote_results.vote_result',         ''),
				'where'         => 'bbvote_results.vote_id = bbvote_desc.vote_id',
				'left_join'     => 'bbvote_desc LEFT JOIN bbtopics ON bbtopics.topic_id = bbvote_desc.topic_id',
			),
			array(
				'target'        => POLL_VOTES_TABLE,
				'primary'       => 'bbvote_desc.topic_id',
				'query_first'   => array('target', $convert->truncate_statement . POLL_VOTES_TABLE),
					array('poll_option_id', VOTE_CONVERTED,               ''),
					array('topic_id',       'bbvote_desc.topic_id',       ''),
					array('vote_user_id',   'bbvote_voters.vote_user_id', 'df_user_id'),
					array('vote_user_ip',   'bbvote_voters.vote_user_ip', 'df_decode_ip'),
				'where'         => 'bbvote_voters.vote_id = bbvote_desc.vote_id',
			),
			array(
				'target'        => WORDS_TABLE,
				'primary'       => 'bbwords.word_id',
				'query_first'   => array('target', $convert->truncate_statement . WORDS_TABLE),
				'autoincrement' => 'word_id',
					array('word_id',     'bbwords.word_id',     ''),
					array('word',        'bbwords.word',        ''),
					array('replacement', 'bbwords.replacement', ''),
			),
			array(
				'target'        => POSTS_TABLE,
				'primary'       => 'bbposts.post_id',
				'autoincrement' => 'post_id',
				'query_first'   => array('target', $convert->truncate_statement . POSTS_TABLE),
				'execute_first' => '
					$config["max_post_chars"] = 0;
					$config["min_post_chars"] = 0;
					$config["max_quote_depth"] = 0;
					phpbb_check_username_collisions();
				',
					array('post_id',          'bbposts.post_id',                           ''),
					array('topic_id',         'bbposts.topic_id',                          ''),
					array('forum_id',         'bbposts.forum_id',                          ''),
					array('poster_id',        'bbposts.poster_id',                         'df_user_id'),
					array('icon_id',          0,                                           ''),
					array('poster_ip',        'bbposts.poster_ip',                         'df_decode_ip'),
					array('post_time',        'bbposts.post_time',                         'df_timezone_correction'),
					array('enable_bbcode',    'bbposts.enable_bbcode',                     ''),
					array('',                 'bbposts.enable_html',                       ''),
					array('enable_smilies',   'bbposts.enable_smilies',                    ''),
					array('enable_sig',       'bbposts.enable_sig',                        ''),
					array('enable_magic_url', 1,                                           ''),
					array('post_username',    'bbposts.post_username',                     ''),
					array('post_subject',     'bbposts_text.post_subject',                 'df_entity_decode'),
					array('post_attachment',  'bbposts.post_attachment',                   ''),
					array('post_edit_time',   'bbposts.post_edit_time',                    array('typecast' => 'int', 'function1' => 'df_timezone_correction')),
					array('post_edit_count',  'bbposts.post_edit_count',                   ''),
					array('post_edit_reason', '',                                          ''),
					array('post_edit_user',   '',                                          'phpbb_post_edit_user'),
					array('bbcode_uid',       'bbposts.post_time',                         'make_uid'),
					array('post_text',        'bbposts_text.post_text',                    'df_prepare_message'),
					array('bbcode_bitfield',  '',                                          'get_bbcode_bitfield'),
					array('post_checksum',    '',                                          ''),
				'where'         => 'bbposts.post_id = bbposts_text.post_id'
			),

			array(
				'target'        => PRIVMSGS_TABLE,
				'primary'       => 'bbprivmsgs.privmsgs_id',
				'autoincrement' => 'msg_id',
				'query_first'   => array(
					array('target', $convert->truncate_statement . PRIVMSGS_TABLE),
					array('target', $convert->truncate_statement . PRIVMSGS_RULES_TABLE),
				),
				'execute_first' => '
					$config["max_post_chars"] = 0;
					$config["min_post_chars"] = 0;
					$config["max_quote_depth"] = 0;
				',
					array('msg_id',              'bbprivmsgs.privmsgs_id',                                ''),
					array('root_level',          0,                                                       ''),
					array('author_id',           'bbprivmsgs.privmsgs_from_userid AS poster_id',          'df_user_id'),
					array('icon_id',             0,                                                       ''),
					array('author_ip',           'bbprivmsgs.privmsgs_ip',                                'df_decode_ip'),
					array('message_time',        'bbprivmsgs.privmsgs_date',                              'df_timezone_correction'),
					array('enable_bbcode',       'bbprivmsgs.privmsgs_enable_bbcode AS enable_bbcode',    ''),
					array('',                    'bbprivmsgs.privmsgs_enable_html AS enable_html',        ''),
					array('enable_smilies',      'bbprivmsgs.privmsgs_enable_smilies AS enable_smilies',  ''),
					array('enable_magic_url',    1,                                                       ''),
					array('enable_sig',          'bbprivmsgs.privmsgs_attach_sig',                        ''),
					array('message_subject',     'bbprivmsgs.privmsgs_subject',                           ''),
					array('message_attachment',  'bbprivmsgs.privmsgs_attachment',                        ''),
					array('message_edit_reason', '',                                                      ''),
					array('message_edit_user',   0,                                                       ''),
					array('message_edit_time',   0,                                                       ''),
					array('message_edit_count',  0,                                                       ''),
					array('bbcode_uid',          'bbprivmsgs.privmsgs_date AS post_time',                 'make_uid'),
					array('message_text',        'bbprivmsgs_text.privmsgs_text',                         'df_prepare_message'),
					array('bbcode_bitfield',    '',                                                       'get_bbcode_bitfield'),
					array('to_address',         'bbprivmsgs.privmsgs_to_userid',                          'df_privmsgs_to_userid'),
					array('bcc_address',        '',                                                       ''),
				'where'         => 'bbprivmsgs.privmsgs_id = bbprivmsgs_text.privmsgs_text_id'
			),
			array(
				'target'        => PRIVMSGS_FOLDER_TABLE,
				'primary'       => 'users.user_id',
				'query_first'   => array('target', $convert->truncate_statement . PRIVMSGS_FOLDER_TABLE),
					array('user_id',     'users.user_id',                    'df_user_id'),
					array('folder_name', $user->lang['CONV_SAVED_MESSAGES'], ''),
					array('pm_count',    0,                                  ''),
				'where'         => 'users.user_id <> 1',
			),
			// Inbox
			array(
				'target'        => PRIVMSGS_TO_TABLE,
				'primary'       => 'bbprivmsgs.privmsgs_id',
				'query_first'   => array('target', $convert->truncate_statement . PRIVMSGS_TO_TABLE),
					array('msg_id',       'bbprivmsgs.privmsgs_id',          ''),
					array('user_id',      'bbprivmsgs.privmsgs_to_userid',   'df_user_id'),
					array('author_id',    'bbprivmsgs.privmsgs_from_userid', 'df_user_id'),
					array('pm_deleted',   0,                                 ''),
					array('pm_new',       'bbprivmsgs.privmsgs_type',        'phpbb_new_pm'),
					array('pm_unread',    'bbprivmsgs.privmsgs_type',        'phpbb_unread_pm'),
					array('pm_replied',   0,                                 ''),
					array('pm_marked',    0,                                 ''),
					array('pm_forwarded', 0,                                 ''),
					array('folder_id',    PRIVMSGS_INBOX,                    ''),
				'where'         => 'bbprivmsgs.privmsgs_id = bbprivmsgs_text.privmsgs_text_id AND (bbprivmsgs.privmsgs_type = 0 OR bbprivmsgs.privmsgs_type = 1 OR bbprivmsgs.privmsgs_type = 5)',
			),
			// Outbox
			array(
				'target'        => PRIVMSGS_TO_TABLE,
				'primary'       => 'bbprivmsgs.privmsgs_id',
					array('msg_id',       'bbprivmsgs.privmsgs_id',          ''),
					array('user_id',      'bbprivmsgs.privmsgs_from_userid', 'df_user_id'),
					array('author_id',    'bbprivmsgs.privmsgs_from_userid', 'df_user_id'),
					array('pm_deleted',   0,                                 ''),
					array('pm_new',       0,                                 ''),
					array('pm_unread',    0,                                 ''),
					array('pm_replied',   0,                                 ''),
					array('pm_marked',    0,                                 ''),
					array('pm_forwarded', 0,                                 ''),
					array('folder_id',    PRIVMSGS_OUTBOX,                   ''),
				'where'         => 'bbprivmsgs.privmsgs_id = bbprivmsgs_text.privmsgs_text_id AND (bbprivmsgs.privmsgs_type = 1 OR bbprivmsgs.privmsgs_type = 5)',
			),
			// Sentbox
			array(
				'target'        => PRIVMSGS_TO_TABLE,
				'primary'       => 'bbprivmsgs.privmsgs_id',
					array('msg_id',       'bbprivmsgs.privmsgs_id',          ''),
					array('user_id',      'bbprivmsgs.privmsgs_from_userid', 'df_user_id'),
					array('author_id',    'bbprivmsgs.privmsgs_from_userid', 'df_user_id'),
					array('pm_deleted',   0,                                 ''),
					array('pm_new',       'bbprivmsgs.privmsgs_type',        'phpbb_new_pm'),
					array('pm_unread',    'bbprivmsgs.privmsgs_type',        'phpbb_unread_pm'),
					array('pm_replied',   0,                                 ''),
					array('pm_marked',    0,                                 ''),
					array('pm_forwarded', 0,                                 ''),
					array('folder_id',    PRIVMSGS_SENTBOX,                  ''),
				'where'         => 'bbprivmsgs.privmsgs_id = bbprivmsgs_text.privmsgs_text_id AND bbprivmsgs.privmsgs_type = 2',
			),
			// Savebox (SAVED IN)
			array(
				'target'        => PRIVMSGS_TO_TABLE,
				'primary'       => 'bbprivmsgs.privmsgs_id',
					array('msg_id',       'bbprivmsgs.privmsgs_id',          ''),
					array('user_id',      'bbprivmsgs.privmsgs_to_userid',   'df_user_id'),
					array('author_id',    'bbprivmsgs.privmsgs_from_userid', 'df_user_id'),
					array('pm_deleted',   0,                                 ''),
					array('pm_new',       'bbprivmsgs.privmsgs_type',        'phpbb_new_pm'),
					array('pm_unread',    'bbprivmsgs.privmsgs_type',        'phpbb_unread_pm'),
					array('pm_replied',   0,                                 ''),
					array('pm_marked',    0,                                 ''),
					array('pm_forwarded', 0,                                 ''),
					array('folder_id',    'bbprivmsgs.privmsgs_to_userid',   'phpbb_get_savebox_id'),
				'where'         => 'bbprivmsgs.privmsgs_id = bbprivmsgs_text.privmsgs_text_id AND bbprivmsgs.privmsgs_type = 3',
			),
			// Savebox (SAVED OUT)
			array(
				'target'        => PRIVMSGS_TO_TABLE,
				'primary'       => 'bbprivmsgs.privmsgs_id',
					array('msg_id',       'bbprivmsgs.privmsgs_id',          ''),
					array('user_id',      'bbprivmsgs.privmsgs_from_userid', 'df_user_id'),
					array('author_id',    'bbprivmsgs.privmsgs_from_userid', 'df_user_id'),
					array('pm_deleted',   0,                                 ''),
					array('pm_new',       'bbprivmsgs.privmsgs_type',        'phpbb_new_pm'),
					array('pm_unread',    'bbprivmsgs.privmsgs_type',        'phpbb_unread_pm'),
					array('pm_replied',   0,                                 ''),
					array('pm_marked',    0,                                 ''),
					array('pm_forwarded', 0,                                 ''),
					array('folder_id',    'bbprivmsgs.privmsgs_from_userid', 'phpbb_get_savebox_id'),
				'where'         => 'bbprivmsgs.privmsgs_id = bbprivmsgs_text.privmsgs_text_id AND bbprivmsgs.privmsgs_type = 4',
			),
			array(
				'target'        => GROUPS_TABLE,
				'autoincrement' => 'group_id',
				'query_first'   => array('target', $convert->truncate_statement . GROUPS_TABLE),
					array('group_id',      'bbgroups.group_id',          ''),
					array('group_type',    'bbgroups.group_type',        'phpbb_convert_group_type'),
					array('group_display', 0,                            ''),
					array('group_legend',  0,                            ''),
					array('group_name',    'bbgroups.group_name',        'phpbb_convert_group_name'),
					array('group_desc',    'bbgroups.group_description', ''),
				'where'         => 'bbgroups.group_single_user = 0',
			),
			array(
				'target'        => USER_GROUP_TABLE,
				'query_first'   => array('target', $convert->truncate_statement . USER_GROUP_TABLE),
				'execute_first' => 'add_default_groups();',
					array('group_id',     'bbgroups.group_id',        ''),
					array('user_id',      'bbgroups.group_moderator', 'df_user_id'),
					array('group_leader', 1,                          ''),
					array('user_pending', 0,                          ''),
				'where'         => 'bbgroups.group_single_user = 0 AND bbgroups.group_moderator <> 0',
			),
			array(
				'target'        => USER_GROUP_TABLE,
					array('group_id',     'bbuser_group.group_id',     ''),
					array('user_id',      'bbuser_group.user_id',      'df_user_id'),
					array('group_leader', 0,                           ''),
					array('user_pending', 'bbuser_group.user_pending', ''),
				'where'         => 'bbuser_group.group_id = bbgroups.group_id AND bbgroups.group_single_user = 0 AND bbgroups.group_moderator <> bbuser_group.user_id',
			),
			array(
				'target'        => USERS_TABLE,
				'primary'       => 'users.user_id',
				'autoincrement' => 'user_id',
				'query_first'   => array(array('target', 'DELETE FROM ' . USERS_TABLE . ' WHERE user_id <> ' . ANONYMOUS), array('target', $convert->truncate_statement . BOTS_TABLE)),
				'execute_last'  => 'remove_invalid_users();',
					array('user_id',                  'users.user_id',                                'df_user_id'),
					array('',                         'users.user_id AS poster_id',                   'df_user_id'),
					array('user_type',                'users.user_active',                            'set_user_type'),
					array('group_id',                 'users.user_level',                             'phpbb_set_primary_group'),
					array('user_regdate',             'users.user_regdate',                           array('function1' => 'df_regdate_timestamp', 'function2' => 'df_timezone_correction')),
					array('username',                 'users.username',                               ''),
					array('username_clean',           'users.username',                               'utf8_clean_string'),
					array('user_password',            'users.user_password',                          'phpbb_hash'),
					array('user_pass_convert',        1,                                              ''),
					array('user_posts',               'users.user_posts',                             'intval'),
					array('user_email',               'users.user_email',                             'strtolower'),
					array('user_email_hash',          'users.user_email',                             'gen_email_hash'),
					array('user_birthday',            '',                                             ''),
					array('user_lastvisit',           'users.user_lastvisit',                         array('function1' => 'intval', 'function2' => 'df_timezone_correction')),
					array('user_lastmark',            'users.user_lastvisit',                         array('function1' => 'intval', 'function2' => 'df_timezone_correction')),
					array('user_lang',                $config['default_lang'],                        ''),
					array('',                         'users.user_lang',                              ''),
					array('user_timezone',            'users.user_timezone',                          'floatval'),
					array('user_dateformat',          'users.user_dateformat',                        'fill_dateformat'),
					array('user_inactive_reason',     '',                                             'phpbb_inactive_reason'),
					array('user_inactive_time',       '',                                             'phpbb_inactive_time'),
					array('user_interests',           'users.user_interests',                         ''),
					array('user_occ',                 'users.user_occ',                               ''),
					array('user_website',             'users.user_website',                           'validate_website'),
					array('user_jabber',              '',                                             ''),
					array('user_msnm',                'users.user_msnm',                              ''),
					array('user_yim',                 'users.user_yim',                               ''),
					array('user_aim',                 'users.user_aim',                               ''),
					array('user_icq',                 'users.user_icq',                               ''),
					array('user_from',                'users.user_from',                              ''),
					array('user_rank',                'users.user_rank',                              'intval'),
					array('user_permissions',         '',                                             ''),
					array('user_avatar',              'users.user_avatar',                            'df_import_avatar'),
					array('user_avatar_type',         'users.user_avatar_type',                       'phpbb_avatar_type'),
					array('user_avatar_width',        'users.user_avatar',                            'df_get_avatar_width'),
					array('user_avatar_height',       'users.user_avatar',                            'df_get_avatar_height'),
					array('user_new_privmsg',         'users.user_new_privmsg',                       ''),
					array('user_unread_privmsg',      0,                                             ''),
					array('user_last_privmsg',        'users.user_last_privmsg',                     'intval'),
					array('user_emailtime',           'users.user_emailtime',                        'null_to_zero'),
					array('user_notify',              'users.user_notify',                           'intval'),
					array('user_notify_pm',           'users.user_notify_pm',                        'intval'),
					array('user_notify_type',         NOTIFY_EMAIL,                                  ''),
					array('user_allow_pm',            'users.user_allow_pm',                         'intval'),
					array('user_allow_viewonline',    'users.user_allow_viewonline',                 'intval'),
					array('user_allow_viewemail',     'users.user_viewemail',                        'intval'),
					array('user_actkey',              'users.user_actkey',                           ''),
					array('user_newpasswd',           '',                                            ''),
					array('user_style',               $config['default_style'],                      ''),
					array('user_options',             '',                                            'set_user_options'),
					array('',                         'users.user_popup_pm AS popuppm',              ''),
					array('',                         'users.user_allowhtml AS html',                ''),
					array('',                         'users.user_allowbbcode AS bbcode',            ''),
					array('',                         'users.user_allowsmile AS smile',              ''),
					array('',                         'users.user_attachsig AS attachsig',           ''),
					array('user_sig_bbcode_uid',      'users.user_regdate',                          'make_uid'),
					array('user_sig',                 'users.user_sig',                              'df_prepare_message'),
					array('user_sig_bbcode_bitfield', '',                                            'get_bbcode_bitfield'),
					array('',                         'users.user_regdate AS post_time',             ''),
				'where'         => 'users.user_id <> 1',
			),
		),
	);
}

?>